package template.cqrs.coreapi.commands;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Builder;
import lombok.Value;
import org.axonframework.modelling.command.TargetAggregateIdentifier;
import template.cqrs.coreapi.common.AlertDetails;
import template.cqrs.coreapi.common.AlertSeverity;

import java.time.Instant;
import java.util.UUID;

@Value // Lombok's @Value makes this an immutable class with getters, equals, hashCode, toString
@Builder // For easier object creation
public class CreateAlertCommand {
    @TargetAggregateIdentifier // Instructs Axon to route this command to the AlertAggregate instance with this ID
    UUID alertId; // Usually generated by the client or command sender for creation

    @NotNull(message = "Severity cannot be null")
    AlertSeverity severity;

    @NotBlank(message = "Description cannot be blank")
    @Size(min = 5, max = 1000, message = "Description must be between 5 and 1000 characters")
    String description;

    @NotBlank(message = "Source cannot be blank")
    @Size(min = 1, max = 255, message = "Source must be between 1 and 255 characters")
    String source;

    // AlertDetails can be null if no extra details are provided
    AlertDetails details; // Using the AlertDetails VO

    // Timestamp for when the event leading to alert creation occurred, if different from system time
    Instant eventTimestamp; // Optional, can be used to reflect original event time

    // User initiating the command, if applicable
    String initiatedBy;
}
